"use client";
import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, CheckCircle2, ClipboardCheck, EyeOff, LoaderCircle, RotateCcw, Scale } from "lucide-react";
import type { BlindReviewAiResult, BlindReviewAnswer } from "@/lib/blind-review";

type ReviewCase={id:string;role:string;criterion:string;jd:string;sources:Array<{id:string;type:"resume"|"interview";text:string}>;title?:string;scenario?:string;expected?:{status:"supported"|"insufficient"|"conflict";scoreRange:[number,number]|null;rationale:string}};
type Resolution={verdict:"ai"|"owner"|"custom";appliedAt:string};
type ReviewSession={id:string;status:"in_progress"|"completed";datasetVersion?:string;isHistorical?:boolean;completed:number;total:number;resolved?:number;cases:ReviewCase[];answers:Record<string,BlindReviewAnswer>;resolutions?:Record<string,Resolution>;report?:{comparedCases:number;statusAgreement:number;citationAgreement:number;averageScoreDifference:number|null;disagreementCaseIds:string[]};model?:{id:string;promptVersion:string}|null;aiResults?:Record<string,BlindReviewAiResult>};
type ReviewData={dataset:{version:string;currentVersion?:string;totalCases:number};session:ReviewSession|null};
const statusLabel={supported:"有证据，可评分",insufficient:"证据不足，低置信度暂估",conflict:"信息冲突，待核实"} as const;

export function BlindReviewPanel({onActiveChange}:{onActiveChange?:(active:boolean)=>void}){
 const [data,setData]=useState<ReviewData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[starting,setStarting]=useState(false),[index,setIndex]=useState(0);
 const load=useCallback(async()=>{try{const response=await fetch("/api/evals/blind-review",{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);onActiveChange?.(body.session?.status==="in_progress");const first=body.session?.cases?.findIndex((item:ReviewCase)=>!body.session.answers[item.id]);setIndex(first>=0?first:0);setError("");}catch(e){setError(e instanceof Error?e.message:"个人盲审加载失败");onActiveChange?.(false);}finally{setLoading(false);}},[onActiveChange]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
 async function start(){setStarting(true);setError("");try{const response=await fetch("/api/evals/blind-review",{method:"POST"}),body=await response.json();if(!response.ok)throw new Error(body.error);setData(body);onActiveChange?.(true);setIndex(0);}catch(e){setError(e instanceof Error?e.message:"暂时无法开始盲审");}finally{setStarting(false);}}
 if(loading)return <section className="hl-blind-shell"><LoaderCircle className="hl-spin" size={20}/><span>正在读取个人盲审进度…</span></section>;
 if(!data?.session)return <section className="hl-blind-start"><div><ClipboardCheck size={25}/><h2>建立你的第一份人工判断基线</h2><p>系统随机抽取20条合成案例，提交前隐藏AI答案。预计15～20分钟，可随时退出继续。</p></div><div className="hl-blind-start-actions"><span><EyeOff size={16}/>本轮记录为“产品负责人复核”，不会冒充HR专家评测。</span><button className="hl-primary" onClick={start} disabled={starting}>{starting?<LoaderCircle className="hl-spin" size={17}/>:<ClipboardCheck size={17}/>}开始个人盲审</button></div>{error&&<p className="hl-blind-error" role="alert">{error}</p>}</section>;
 const session=data.session;
 if(session.status==="completed")return <ReviewReport session={session} currentVersion={data.dataset.currentVersion||data.dataset.version} onRestart={start} onUpdate={setData} restarting={starting} error={error}/>;
 const item=session.cases[index];
 return <section className="hl-blind-review"><header><div><span>个人盲审 · 产品负责人复核</span><h2>{session.completed===session.total?"20条已完成，可以提交":"只看原文，先做自己的判断"}</h2><p>已保存 {session.completed}/{session.total} 条。提交前不会显示AI结果或设计标注。</p></div><strong>{index+1}<small> / {session.total}</small></strong></header><div className="hl-blind-progress" aria-label={`已完成 ${session.completed} 条`}><i style={{width:`${session.completed/session.total*100}%`}}/></div>
  {session.completed===session.total?<CompleteReview sessionId={session.id} onComplete={(next)=>{setData(next);onActiveChange?.(false);}} setError={setError}/>:item?<ReviewForm key={item.id} sessionId={session.id} item={item} answer={session.answers[item.id]} onSaved={(next)=>{setData(next);const nextSession=next.session;if(!nextSession)return;const nextIndex=nextSession.cases.findIndex((entry:ReviewCase)=>!nextSession.answers[entry.id]);setIndex(nextIndex>=0?nextIndex:Math.min(index+1,session.total-1));}}/>:null}
  <footer className="hl-blind-nav"><button className="hl-secondary" disabled={index===0} onClick={()=>setIndex(value=>value-1)}><ArrowLeft size={16}/>上一条</button><span>每次点击“保存并下一条”都会写入数据库</span><button className="hl-secondary" disabled={index===session.total-1} onClick={()=>setIndex(value=>value+1)}>下一条<ArrowRight size={16}/></button></footer>{error&&<p className="hl-blind-error" role="alert">{error}</p>}
 </section>;
}

function ReviewForm({sessionId,item,answer,onSaved}:{sessionId:string;item:ReviewCase;answer?:BlindReviewAnswer;onSaved:(data:ReviewData)=>void}){
 const [status,setStatus]=useState<BlindReviewAnswer["status"]>(answer?.status||"supported"),[score,setScore]=useState(answer?.score??60),[sourceIds,setSourceIds]=useState(answer?.sourceIds||[]),[reason,setReason]=useState(answer?.reason||""),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const toggle=(id:string)=>setSourceIds(values=>values.includes(id)?values.filter(value=>value!==id):[...values,id]);
 async function save(){setSaving(true);setError("");try{const response=await fetch("/api/evals/blind-review",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"save",sessionId,caseId:item.id,status,score:status==="conflict"?null:score,sourceIds,reason})}),body=await response.json();if(!response.ok)throw new Error(body.error);onSaved(body);}catch(e){setError(e instanceof Error?e.message:"保存失败，请重试");}finally{setSaving(false);}}
 return <div className="hl-blind-case"><div className="hl-blind-context"><div><span>岗位</span><strong>{item.role}</strong></div><div><span>本条只评价</span><strong>{item.criterion}</strong></div><details><summary>查看岗位要求</summary><p>{item.jd}</p></details></div>
  <div className="hl-blind-sources"><h3>候选人原文</h3>{item.sources.length?item.sources.map((source,sourceIndex)=><label key={source.id} className={sourceIds.includes(source.id)?"is-selected":""}><input type="checkbox" checked={sourceIds.includes(source.id)} onChange={()=>toggle(source.id)}/><div><span>{source.type==="resume"?"简历":"面试记录"} · 原文 {sourceIndex+1}</span><p>{source.text}</p></div></label>):<p className="hl-help">本案例没有可供判断的原文。</p>}</div>
  <details className="hl-blind-rubric"><summary>不确定怎么判断？查看评分参考</summary><ul><li><strong>70～89：</strong>目标岗位直接经验，有明确行动和结果。</li><li><strong>50～69：</strong>直接相关，但过程或结果不完整。</li><li><strong>30～49：</strong>其他行业或场景的经验可以迁移。</li><li><strong>10～29：</strong>有真实行动，但与本维度关联很弱。</li><li><strong>不评分：</strong>只有课程、自评、身份信息，或来源直接冲突。</li></ul></details>
  <fieldset className="hl-blind-status"><legend>你的判断</legend>{Object.entries(statusLabel).map(([value,label])=><label key={value} className={status===value?"is-active":""}><input type="radio" name={`status-${item.id}`} value={value} checked={status===value} onChange={()=>{const next=value as BlindReviewAnswer["status"];setStatus(next);if(next==="insufficient")setScore(current=>Math.min(current,24));}}/><span>{label}</span></label>)}</fieldset>
  {status!=="conflict"&&<label className="hl-blind-score">{status==="insufficient"?"当前材料匹配暂估分（0～24）":"人工评分（0～100）"}<input type="number" min="0" max={status==="insufficient"?24:100} value={score} onChange={event=>setScore(Number(event.target.value))}/><small>{status==="insufficient"?"低分表示当前材料缺少支撑，不代表候选人的真实能力。":"评价当前维度，不是候选人的总体优秀程度。"}</small></label>}
  <label className="hl-blind-reason">判断理由<textarea rows={3} maxLength={300} value={reason} onChange={event=>setReason(event.target.value)} placeholder="例如：有跨行业的具体行动，但没有目标岗位直接应用，因此按可迁移经验评分。"/></label>
  <div className="hl-blind-save"><span role="status">{error||answer?"本条已有保存记录，可继续修改。":"选择原文并写一句判断依据。"}</span><button className="hl-primary" onClick={save} disabled={saving}>{saving?<LoaderCircle className="hl-spin" size={16}/>:<ArrowRight size={16}/>}保存并下一条</button></div>
 </div>;
}

function CompleteReview({sessionId,onComplete,setError}:{sessionId:string;onComplete:(data:ReviewData)=>void;setError:(value:string)=>void}){const [saving,setSaving]=useState(false);async function complete(){setSaving(true);try{const response=await fetch("/api/evals/blind-review",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"complete",sessionId})}),body=await response.json();if(!response.ok)throw new Error(body.error);onComplete(body);}catch(e){setError(e instanceof Error?e.message:"提交失败，请重试");}finally{setSaving(false);}}return <div className="hl-blind-finish"><CheckCircle2 size={30}/><h3>你的20条判断已经全部保存</h3><p>提交后才会解锁AI答案，并生成状态、分数和引用的一致性报告。提交后本轮不能修改。</p><button className="hl-primary" onClick={complete} disabled={saving}>{saving?<LoaderCircle className="hl-spin" size={17}/>:<ClipboardCheck size={17}/>}提交盲审并查看结果</button></div>}

function ReviewReport({session,currentVersion,onRestart,onUpdate,restarting,error}:{session:ReviewSession;currentVersion:string;onRestart:()=>void;onUpdate:(data:ReviewData)=>void;restarting:boolean;error:string}){
 const report=session.report,disagreements=new Set(report?.disagreementCaseIds||[]);
 return <section className="hl-blind-report"><header><div><CheckCircle2 size={24}/><div><h2>个人盲审已完成</h2><p>这是产品负责人判断与本轮AI输出的差异，不代表真实HR准确率。</p></div></div><button className="hl-secondary" onClick={onRestart} disabled={restarting}>{restarting?<LoaderCircle className="hl-spin" size={16}/>:<RotateCcw size={16}/>}开始新一轮</button></header>
  {session.isHistorical&&<div className="hl-blind-history-note"><strong>这是数据集 {session.datasetVersion} 的历史盲审</strong><p>当前案例已升级到 {currentVersion}，旧结果仍保留；开始新一轮会使用去重后的新案例。</p></div>}
  {report?<><div className="hl-blind-metrics"><div><span>状态一致率</span><strong>{report.statusAgreement.toFixed(1)}%</strong></div><div><span>引用选择一致率</span><strong>{report.citationAgreement.toFixed(1)}%</strong></div><div><span>平均分差</span><strong>{report.averageScoreDifference===null?"—":`${report.averageScoreDifference.toFixed(1)} 分`}</strong></div><div><span>待确认分歧</span><strong>{Math.max(0,report.disagreementCaseIds.length-(session.resolved||0))} 条</strong></div></div><div className="hl-calibration-explainer"><Scale size={20}/><div><strong>确认后才会产生影响</strong><p>你的选择会更新本数据集的设计标注，用于该版本下一次模型评测；不会自动修改招聘任务评分、模型参数或历史结果。</p></div></div><details className="hl-blind-differences" open><summary>逐条处理人机分歧（{session.resolved||0}/{report.disagreementCaseIds.length}）</summary>{session.cases.filter(item=>disagreements.has(item.id)).map(item=>{const own=session.answers[item.id],ai=session.aiResults?.[item.id],resolution=session.resolutions?.[item.id];return <article key={item.id}><h3>{item.role} · {item.criterion}</h3><div><p><span>你的判断</span><strong>{statusLabel[own.status]}{own.score!==null?` · ${own.score}分`:""}</strong></p><p><span>AI判断</span><strong>{ai?`${statusLabel[ai.status]}${ai.score!==null?` · ${ai.score}分`:""}`:"本轮无可用结果"}</strong></p><p><span>设计标注</span><strong>{item.expected?`${statusLabel[item.expected.status]}${item.expected.scoreRange?` · ${item.expected.scoreRange[0]}～${item.expected.scoreRange[1]}分`:""}`:"—"}</strong></p></div><p>{ai?.claim}</p><details><summary>查看设计标注依据</summary><p>{item.expected?.rationale}</p></details><CalibrationDecision sessionId={session.id} item={item} answer={own} ai={ai} resolution={resolution} onUpdated={onUpdate}/></article>})}</details></>:<p className="hl-help">当前数据集还没有可对照的AI运行结果。</p>}
  <small>对照模型：{session.model?`${session.model.id} / ${session.model.promptVersion}`:"暂无"}</small>{error&&<p className="hl-blind-error" role="alert">{error}</p>}
 </section>;
}

function CalibrationDecision({sessionId,item,answer,ai,resolution,onUpdated}:{sessionId:string;item:ReviewCase;answer:BlindReviewAnswer;ai?:BlindReviewAiResult;resolution?:Resolution;onUpdated:(data:ReviewData)=>void}){
 const [customOpen,setCustomOpen]=useState(false),[status,setStatus]=useState<BlindReviewAnswer["status"]>(answer.status),[score,setScore]=useState(answer.score??60),[sourceIds,setSourceIds]=useState(answer.sourceIds),[rationale,setRationale]=useState(answer.reason),[saving,setSaving]=useState(false),[message,setMessage]=useState("");
 async function resolve(verdict:"ai"|"owner"|"custom"){setSaving(true);setMessage("");try{const custom=verdict==="custom"?{status,score:status==="conflict"?null:score,sourceIds,rationale}:undefined,response=await fetch("/api/evals/blind-review",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"resolve",sessionId,caseId:item.id,verdict,custom})}),body=await response.json();if(!response.ok)throw new Error(body.error);setMessage("已更新这条案例的设计标注。");onUpdated(body);}catch(e){setMessage(e instanceof Error?e.message:"暂时无法应用这次校准");}finally{setSaving(false);}}
 const toggle=(id:string)=>setSourceIds(values=>values.includes(id)?values.filter(value=>value!==id):[...values,id]);
 if(resolution)return <div className="hl-calibration-done"><CheckCircle2 size={16}/><span>已确认并应用：{resolution.verdict==="ai"?"AI判断更合理":resolution.verdict==="owner"?"我的判断更合理":"使用重新修改的判断"}</span></div>;
 return <div className="hl-calibration"><strong>最终以哪个判断作为标注？</strong><div className="hl-calibration-actions"><button className="hl-secondary" disabled={saving||!ai} onClick={()=>resolve("ai")}>AI更合理</button><button className="hl-secondary" disabled={saving} onClick={()=>resolve("owner")}>我的判断更合理</button><button className="hl-secondary" disabled={saving} onClick={()=>setCustomOpen(value=>!value)}>两者都需修改</button></div>{customOpen&&<div className="hl-calibration-custom"><label>修改后的判断<select value={status} onChange={event=>{const next=event.target.value as BlindReviewAnswer["status"];setStatus(next);if(next==="insufficient")setScore(current=>Math.min(current,24));}}>{Object.entries(statusLabel).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>{status!=="conflict"&&<label>{status==="insufficient"?"暂估中心分":"合理中心分"}<input type="number" min="0" max={status==="insufficient"?24:100} value={score} onChange={event=>setScore(Number(event.target.value))}/><small>{status==="insufficient"?"只表示当前材料匹配度，上限24分。":"系统会形成上下浮动10分的合理区间。"}</small></label>}<fieldset><legend>支持判断的原文</legend>{item.sources.map(source=><label key={source.id}><input type="checkbox" checked={sourceIds.includes(source.id)} onChange={()=>toggle(source.id)}/>{source.type==="resume"?"简历原文":"面试原文"}</label>)}</fieldset><label>修改依据<textarea rows={3} maxLength={500} value={rationale} onChange={event=>setRationale(event.target.value)}/></label><button className="hl-primary" disabled={saving} onClick={()=>resolve("custom")}>{saving?<LoaderCircle className="hl-spin" size={16}/>:null}应用修改</button></div>}<small role="status">{message}</small></div>;
}
