"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { CalendarDays, Copy, Mail } from "lucide-react";
import { noticeStatusLabel, type NoticeRecord } from "@/lib/interview-notice";

export function InterviewNoticePanel({ taskId, candidateId, candidateName, disabled }: { taskId: string; candidateId: string; candidateName: string; disabled: boolean }) {
  const [form, setForm] = useState({ email: "", salutation: candidateName.replace(/（合成）/g, ""), startsAt: "", durationMinutes: 45, location: "", note: "" });
  const [configured, setConfigured] = useState(false); const [from, setFrom] = useState<string | null>(null); const [items, setItems] = useState<NoticeRecord[]>([]); const [contactEmails,setContactEmails]=useState<string[]>([]); const [contactsLoaded,setContactsLoaded]=useState(false); const [manualEmail,setManualEmail]=useState(false); const [preview, setPreview] = useState<NoticeRecord | null>(null); const [checked, setChecked] = useState(false); const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [copied, setCopied] = useState(false);
  async function load() { const response = await fetch(`/api/tasks/${taskId}/notifications?candidateId=${candidateId}`); const data = await response.json(); if (!response.ok) throw Error(data.error); const emails=Array.isArray(data.contactEmails)?data.contactEmails:[]; setConfigured(data.configured); setFrom(data.from); setItems(data.items); setContactEmails(emails); setContactsLoaded(true); setManualEmail(current=>current||emails.length===0); setForm(current=>current.email||emails.length!==1?current:{...current,email:emails[0]}); }
  useEffect(() => { let active=true;fetch(`/api/tasks/${taskId}/notifications?candidateId=${candidateId}`).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error);if(active){const emails=Array.isArray(data.contactEmails)?data.contactEmails:[];setConfigured(data.configured);setFrom(data.from);setItems(data.items);setContactEmails(emails);setContactsLoaded(true);setManualEmail(emails.length===0);setForm(current=>({...current,email:emails.length===1?emails[0]:""}));}}).catch(error=>{if(active){setContactsLoaded(true);setError(error.message);}});return()=>{active=false;}; }, [taskId, candidateId]);
  function update(key: keyof typeof form, value: string | number) { setForm(current => ({ ...current, [key]: value })); setPreview(null); setChecked(false); setCopied(false); }
  async function request(body: unknown) { setBusy("正在处理…"); setError(""); try { const response = await fetch(`/api/tasks/${taskId}/notifications`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw Error(data.error); setPreview(data); await load(); return data as NoticeRecord; } catch (error) { setError((error as Error).message); } finally { setBusy(""); } }
  async function copy() { if (!preview) return; try { await navigator.clipboard.writeText(`${preview.payload.subject}\n\n${preview.payload.text}`); setCopied(true); } catch { setError("浏览器未允许复制，请手动选择预览文字。"); } }
  return <section className="hl-notice"><header className="hl-section-title"><div><h3>安排并通知面试</h3><p>填写时间和腾讯会议链接，先预览，再由你确认发送。联系方式不会进入评分模型。</p></div>{configured ? <span className="hl-success">发件邮箱：{from}</span> : <Link className="hl-secondary" href="/settings/mail">配置发信邮箱</Link>}</header>
    {!contactsLoaded?<p className="hl-help">正在读取简历中的联系方式…</p>:!manualEmail&&contactEmails.length===1?<div className="hl-contact-found"><div><strong>候选人邮箱</strong><span>{form.email}</span><small>已从简历提取并单独加密保存，仅用于通知。</small></div><button type="button" className="hl-quiet" disabled={disabled} onClick={()=>setManualEmail(true)}>更换邮箱</button></div>:!manualEmail&&contactEmails.length>1?<label>选择候选人邮箱<select required disabled={disabled} value={form.email} onChange={event=>update("email",event.target.value)}><option value="">简历中识别到多个邮箱，请选择</option>{contactEmails.map(email=><option value={email} key={email}>{email}</option>)}</select><small>多个邮箱不会自动决定，以免通知错人。</small></label>:<label>候选人邮箱<input type="email" required maxLength={254} disabled={disabled} value={form.email} onChange={event => update("email", event.target.value)} placeholder="简历中未识别到邮箱，请补充"/><small>{contactEmails.length?<button type="button" className="hl-inline-action" onClick={()=>{setManualEmail(false);update("email",contactEmails.length===1?contactEmails[0]:"");}}>使用简历邮箱</button>:"这份简历没有识别到邮箱，只需在这里补充一次。"}</small></label>}
    <label>邮件称呼<input required maxLength={60} disabled={disabled} value={form.salutation} onChange={event => update("salutation", event.target.value)}/></label>
    <div className="hl-two"><label>面试开始时间<input type="datetime-local" required disabled={disabled} value={form.startsAt} onChange={event => update("startsAt", event.target.value)}/></label><label>预计时长<select disabled={disabled} value={form.durationMinutes} onChange={event => update("durationMinutes", Number(event.target.value))}><option value={30}>30 分钟</option><option value={45}>45 分钟</option><option value={60}>60 分钟</option><option value={90}>90 分钟</option></select></label></div>
    <label>会议链接或面试地址<input required maxLength={1000} disabled={disabled} value={form.location} onChange={event => update("location", event.target.value)} placeholder="粘贴腾讯会议链接，或填写线下面试地址"/></label><label>补充说明（可选）<textarea rows={3} maxLength={2000} disabled={disabled} value={form.note} onChange={event => update("note", event.target.value)} placeholder="例如：请提前 5 分钟进入会议。"/></label>
    {error && <p className="hl-error" role="alert">{error}</p>}
    <button className="hl-secondary" disabled={disabled || !!busy || !form.email || !form.startsAt || !form.location} onClick={() => request({ action: "preview", candidateId, details: { ...form, startsAt: new Date(form.startsAt).toISOString() } })}><Mail size={16}/>生成通知预览</button>
    {preview && <div className="hl-mail-preview"><strong>{preview.payload.subject}</strong><pre>{preview.payload.text}</pre><div className="hl-footer-action"><button className="hl-quiet" onClick={copy}><Copy size={15}/>{copied ? "已复制" : "复制通知"}</button>{preview.status === "draft" && <div>{configured ? <><label className="hl-checkbox"><input type="checkbox" checked={checked} onChange={event => setChecked(event.target.checked)}/>我已核对收件人、时间和会议链接。</label><button className="hl-primary" disabled={!checked || !!busy} onClick={() => request({ action: "send", noticeId: preview.id, confirmed: true })}>{busy || "确认发送邮件"}</button></> : <span>尚未配置邮箱，可先复制通知。</span>}</div>}</div><p className="hl-help">{noticeStatusLabel[preview.status]}</p></div>}
    {!!items.length && <details className="hl-technical"><summary>查看通知记录（{items.length}）</summary>{items.map(item => <p key={item.id}><CalendarDays size={14}/>{new Date(item.payload.startsAt).toLocaleString("zh-CN")} · {item.email} · {noticeStatusLabel[item.status]}</p>)}</details>}
  </section>;
}
