"use client";
import { useEffect, useState } from "react";

type Saved = { configured: boolean; host?: string; port?: number; username?: string; fromEmail?: string; displayName?: string };
const providers = { qq: { host: "smtp.qq.com", port: 465 }, netease: { host: "smtp.163.com", port: 465 }, aliyun: { host: "smtp.qiye.aliyun.com", port: 465 }, custom: { host: "", port: 465 } };
export function MailSettings() {
  const [saved, setSaved] = useState<Saved | null>(null); const [provider, setProvider] = useState<keyof typeof providers>("qq");
  const [form, setForm] = useState({ host: "smtp.qq.com", port: 465, username: "", password: "", fromEmail: "", displayName: "招聘团队" }); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { let active=true;fetch("/api/settings/mail").then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.error);if(active){setSaved(data);if(data.configured){setProvider("custom");setForm(value=>({...value,host:data.host,port:data.port,username:data.username,fromEmail:data.fromEmail,displayName:data.displayName}));}}}).catch(error=>{if(active)setError(error.message);});return()=>{active=false;}; }, []);
  function update<K extends keyof typeof form>(key: K, value: typeof form[K]) { setForm(current => ({ ...current, [key]: value })); setMessage(""); }
  async function save(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); setMessage(""); try { const response = await fetch("/api/settings/mail", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw Error(data.error); setForm(value => ({ ...value, password: "" })); setSaved({ configured: true, ...form }); setMessage("连接验证通过，发信邮箱已保存。授权码不会回显。"); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }
  async function remove() { if (!confirm("移除发信邮箱配置？已保存的通知记录不会删除，但之后不能继续发信。")) return; setBusy(true); try { const response = await fetch("/api/settings/mail", { method: "DELETE" }); const data = await response.json(); if (!response.ok) throw Error(data.error); setSaved({ configured: false }); setForm(value => ({ ...value, username: "", password: "", fromEmail: "" })); setMessage("发信邮箱配置已移除。"); } catch (error) { setError((error as Error).message); } finally { setBusy(false); } }
  return <div className="hl-settings"><header className="hl-section-intro"><h1>发信邮箱设置</h1><p>使用你自己的邮箱向候选人发送面试通知。保存前会验证 SMTP 登录；授权码加密保存，不会在页面或日志中显示。</p></header>
    {saved?.configured && <p className="hl-success">当前已配置：{saved.fromEmail}</p>}{error && <p className="hl-error" role="alert">{error}</p>}{message && <p role="status">{message}</p>}
    <form className="hl-mail-form" onSubmit={save}><label>邮箱服务商<select value={provider} onChange={event => { const key = event.target.value as keyof typeof providers; setProvider(key); update("host", providers[key].host); update("port", providers[key].port); }}><option value="qq">QQ 邮箱</option><option value="netease">163 邮箱</option><option value="aliyun">阿里企业邮箱</option><option value="custom">企业邮箱 / 其他</option></select></label>
      <div className="hl-two"><label>SMTP 服务器<input required maxLength={253} value={form.host} onChange={event => update("host", event.target.value)} placeholder="smtp.example.com"/></label><label>端口<select value={form.port} onChange={event => update("port", Number(event.target.value))}><option value={465}>465（SSL/TLS）</option><option value={587}>587（STARTTLS）</option></select></label></div>
      <label>邮箱账号<input required autoComplete="username" maxLength={254} value={form.username} onChange={event => update("username", event.target.value)} placeholder="通常填写完整邮箱地址"/></label>
      <label>邮箱授权码<input required type="password" autoComplete="new-password" maxLength={500} value={form.password} onChange={event => update("password", event.target.value)} placeholder={saved?.configured ? "重新保存时请填写新的授权码" : "不是网页登录密码"}/><small>请在邮箱后台开启 SMTP 并生成授权码。不要把授权码发给任何人。</small></label>
      <div className="hl-two"><label>发件邮箱<input required type="email" maxLength={254} value={form.fromEmail} onChange={event => update("fromEmail", event.target.value)}/></label><label>发件人名称<input required maxLength={60} value={form.displayName} onChange={event => update("displayName", event.target.value)}/></label></div>
      <div className="hl-footer-action"><span>点击保存会连接邮箱服务器验证配置，不会发送测试邮件。</span><div>{saved?.configured && <button type="button" className="hl-quiet" disabled={busy} onClick={remove}>移除配置</button>}<button className="hl-primary" disabled={busy}>{busy ? "正在验证…" : "验证并保存"}</button></div></div>
    </form></div>;
}
