"use client";
import { useEffect,useState } from "react";
type Data={title:string;synthetic:boolean;questions:{id:string;text:string}[];answers:Record<string,string>;complete:boolean;started:boolean};
export function PublicInterview({token}:{token:string}){
 const [data,setData]=useState<Data|null>(null);const [answers,setAnswers]=useState<Record<string,string>>({});const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [notice,setNotice]=useState("");const [recording,setRecording]=useState<string|null>(null);
 useEffect(()=>{fetch("/api/respond/"+token).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setAnswers(d.answers);}).catch(e=>setError(e.message));},[token]);
 async function save(complete:boolean,start=false){setBusy(true);setError("");try{const r=await fetch("/api/respond/"+token,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(start?{}:{answers,complete})});const d=await r.json();if(!r.ok)throw Error(d.error);setData(v=>v?{...v,started:true,complete:!!d.complete}:v);setNotice(complete?"回答已提交。":"进度已保存，可在此浏览器继续。");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function voice(id:string){if(!window.webkitSpeechRecognition){setError("当前浏览器不支持语音识别，请使用文字输入。");return;}const engine=new window.webkitSpeechRecognition();engine.lang="zh-CN";engine.interimResults=false;engine.continuous=false;engine.onresult=e=>setAnswers(v=>({...v,[id]:(v[id]||"")+e.results[0][0].transcript}));engine.onend=()=>setRecording(null);engine.onerror=()=>{setRecording(null);setError("未能识别语音，请检查麦克风权限，或改用文字输入。");};setRecording(id);engine.start();}
 return <main className="hl-public"><div className="hl-brand">MeritTrace</div>{error&&<p role="alert" className="hl-error">{error}</p>}{!data?(!error&&<p role="status">正在读取面试信息…</p>):<><h1>{data.complete?"面试记录已提交":data.title}</h1><p>{data.synthetic?"合成体验 · 请勿填写真实个人信息。":"回答仅用于这次招聘评估。"}</p>{data.complete?<p>感谢完成作答。招聘负责人将综合你的简历与回答审核，后续由对方联系你。</p>:!data.started?<><p>共 {data.questions.length} 道题。开始后链接绑定当前浏览器；可保存草稿并在48小时内返回继续。</p><button className="hl-primary" disabled={busy} onClick={()=>save(false,true)}>开始作答</button></>:<><p>请描述具体经历，无法回答可以直接说明。提交前可修改回答。</p>{data.questions.map((q,i)=><label key={q.id}><strong>问题 {i+1} · {q.text}</strong><textarea rows={5} value={answers[q.id]||""} maxLength={6000} disabled={busy} onChange={e=>setAnswers({...answers,[q.id]:e.target.value})}/><button className="hl-quiet" disabled={busy||!!recording} onClick={()=>voice(q.id)}>{recording===q.id?"正在聆听…":"语音输入"}</button></label>)}<div className="hl-public-actions"><button className="hl-secondary" disabled={busy} onClick={()=>save(false)}>保存草稿</button><button className="hl-primary" disabled={busy||data.questions.some(q=>!answers[q.id]?.trim())} onClick={()=>save(true)}>确认提交回答</button></div><p role="status">{busy?"正在保存…":notice}</p></>}</>}</main>;
}
