import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const {chromium}=require('C:/Users/lhw/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const browser=await chromium.launch({channel:'msedge',headless:true});
try{
 const context=await browser.newContext({viewport:{width:1440,height:1000}});const base='http://localhost:3000';
 const login=await context.request.post(base+'/api/auth/login',{data:{email:process.env.HR_ADMIN_EMAIL||'admin@hirelens.local',password:process.env.HR_ADMIN_PASSWORD||'hirelens-demo'}});assert.equal(login.status(),200);
 await context.route('**/api/settings/mail',route=>route.fulfill({status:200,contentType:'application/json',body:'{"configured":false}'}));
 const id='11111111-1111-4111-8111-111111111111',candidateId='22222222-2222-4222-8222-222222222222';
 const task={id,version:1,updatedAt:new Date().toISOString(),data:{id,title:'财务 AI 产品经理 · 合成界面验收',jd:'合成岗位',synthetic:true,confirmed:true,criteria:[{id:'a',name:'业务理解',description:'合成标准',weight:100}],candidates:[{id:candidateId,name:'候选人 A（合成）',synthetic:true,filename:'synthetic',resume:'合成简历正文',resumeConfirmed:true,sources:[],questions:[],answers:{},interviewComplete:false,shortlisted:true,screening:{summary:'合成评分',scores:[{criterionId:'a',score:70,claim:'合成结论',sourceIds:[],status:'supported'}],conflicts:[],model:'test',latencyMs:1,inputTokens:1,outputTokens:1,createdAt:new Date().toISOString(),scoringVersion:'resume-match-v2',retrieval:{mode:'hybrid',algorithm:'rrf-mmr-v1',cacheHit:false,indexedChunks:1,latencyMs:1,queries:[]}}}],audit:[]}};
 await context.route(`**/api/tasks/${id}/notifications**`,async route=>{if(route.request().method()==='GET')return route.fulfill({status:200,contentType:'application/json',body:'{"configured":false,"from":null,"contactEmails":["candidate@example.com"],"items":[]}'});const body=route.request().postDataJSON();const payload={...body.details,subject:'面试通知｜财务 AI 产品经理 · 合成界面验收',text:'候选人 A，您好：\n\n邀请您参加面试。\n时间：2029年12月01日 10:00（北京时间 UTC+8）\n预计时长：45 分钟\n会议链接或面试地址：https://meeting.example/123'};return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({id:'33333333-3333-4333-8333-333333333333',candidateId,email:body.details.email,payload,status:'draft',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()})});});
 await context.route(`**/api/tasks/${id}`,route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(task)}));
 const page=await context.newPage();await page.goto(base+'/settings/mail');await page.getByRole('heading',{name:'发信邮箱设置'}).waitFor();await page.screenshot({path:'.impeccable/review/mail-settings-desktop.png',fullPage:true});
 await page.goto(base+'/tasks/'+id);await page.getByRole('heading',{name:'安排并通知面试'}).waitFor();await page.getByText('已从简历提取并单独加密保存').waitFor();assert.equal(await page.getByText('candidate@example.com').count(),1);await page.getByLabel('面试开始时间').fill('2029-12-01T10:00');await page.getByLabel('会议链接或面试地址').fill('https://meeting.example/123');await page.getByRole('button',{name:'生成通知预览'}).click();await page.getByText('预览草稿 · 尚未发送').waitFor();await page.screenshot({path:'.impeccable/review/mail-notice-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.reload();await page.getByRole('heading',{name:'安排并通知面试'}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'.impeccable/review/mail-notice-mobile.png',fullPage:true});
 console.log('PASS mail settings and interview notice desktop/mobile UI; preview only, no email sent');
}finally{await browser.close();}
